version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  userbot:
    build: ./userbot/
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - redis
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
      - tg_bot

